FROM golang:1.24@sha256:d9db32125db0c3a680cfb7a1afcaefb89c898a075ec148fdc2f0f646cc2ed509 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o echo-server ./cmd/server
FROM scratch
COPY --from=builder /app/echo-server /
ENTRYPOINT ["/echo-server"]