FROM golang:1.24@sha256:ceb568d0de81fbef40ce4fee77eab524a0a0a8536065c51866ad8c59b7a912cf AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o flow-generator ./cmd/client
FROM scratch
COPY --from=builder /app/flow-generator /
ENTRYPOINT ["/flow-generator"]