FROM golang:1.24@sha256:18a1f2d1e1d3c49f27c904e9182375169615c65852ace724987929b910195b2c AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o echo-server ./cmd/server
FROM scratch
COPY --from=builder /app/echo-server /
ENTRYPOINT ["/echo-server"]