apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flow-generator
  template:
    metadata:
      labels:
        app: flow-generator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - flow-generator
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: flow-generator
        image: ghcr.io/philipschmid/flow-generator:main
        args:
        - "--server=echo-service"
        - "--tcp_ports=8080"
        - "--rate=5"
        - "--max_concurrent=50"
        - "--constant_flows=true"
        ports:
        - containerPort: 9090
          name: metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5