apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flow-generator
  template:
    metadata:
      labels:
        app: flow-generator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - flow-generator
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: flow-generator
        image: ghcr.io/philipschmid/flow-generator:main
        args:
        - "--server=echo-service"
        - "--tcp_ports=8080,8443"
        - "--udp_ports=53,123"
        - "--rate=20"
        - "--max_concurrent=200"
        - "--protocol=both"
        - "--min_duration=1"
        - "--max_duration=5"