apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - echo-server
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: echo-server
        image: ghcr.io/philipschmid/echo-server:main
        ports:
        - containerPort: 80
        - containerPort: 21
        - containerPort: 25
        - containerPort: 443
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 53
          protocol: UDP
        - containerPort: 123
          protocol: UDP
        - containerPort: 69
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  selector:
    app: echo-server
  ports:
  - name: tcp-80
    protocol: TCP
    port: 80
    targetPort: 80
  - name: tcp-21
    protocol: TCP
    port: 21
    targetPort: 21
  - name: tcp-25
    protocol: TCP
    port: 25
    targetPort: 25
  - name: tcp-443
    protocol: TCP
    port: 443
    targetPort: 443
  - name: tcp-8080
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: tcp-8443
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: udp-53
    protocol: UDP
    port: 53
    targetPort: 53
  - name: udp-123
    protocol: UDP
    port: 123
    targetPort: 123
  - name: udp-69
    protocol: UDP
    port: 69
    targetPort: 69